
#include "swindows.h"



//1/sqrt(x)
void fp_sqrtinv_test(fp *x)
{
    fp t[31], tt;
    int i;
    // Precomputed table
    fp_sq2(&tt, x);
    fp_mul3(&t[0], x, &tt);
    for (i = 0; i <= 29; i++) fp_mul3(&t[i+1], &t[i], &tt);

    fp_copy(&tt, &t[0]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[26]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[4]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[4]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[14]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[22]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[29]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[28]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[11]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[4]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[6]);
    for (i = 0; i < 10; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[21]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[22]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[30]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[5]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[6]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[9]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[14]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[4]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[5]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[1]);
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[18]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[21]);
    for (i = 0; i < 4; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[4]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[11]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[7]);
    for (i = 0; i < 16; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[17]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[15]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[11]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[19]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[8]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[19]);
    for (i = 0; i < 2; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[0]);
    for (i = 0; i < 10; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[23]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[22]);
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[30]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[22]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[0]);
    for (i = 0; i < 10; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[18]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[3]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[15]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[21]);
    for (i = 0; i < 3; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[1]);
    for (i = 0; i < 10; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[18]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[12]);
    for (i = 0; i < 10; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[30]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[28]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[25]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[8]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[20]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[9]);
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[26]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[23]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[16]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[7]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[15]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[15]);
    for (i = 0; i < 11; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[15]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[25]);
    for (i = 0; i < 4; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[5]);
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[19]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[5]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[12]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[24]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[11]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[13]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[11]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[19]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[26]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[13]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[8]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[10]);
    for (i = 0; i < 10; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[16]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[14]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[3]);

    fp_sq2(x,&tt);
}

void fp_sqrt_test(fp *y, fp *x)
{
    fp t[31], tt;
    int i;
    // Precomputed table
    fp_sq2(&tt, x);
    fp_mul3(&t[0], x, &tt);
    for (i = 0; i <= 29; i++) fp_mul3(&t[i+1], &t[i], &tt);

    fp_copy(&tt, x);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[3]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[27]);   
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[11]); 
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[19]); 
    for (i = 0; i < 4; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[5]); 
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[5]); 
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[30]); 
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[8]); 
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[28]); 
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[17]); 
    for (i = 0; i < 4; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[3]); 
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[17]); 
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[9]); 
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[16]); 
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[17]); 
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[23]); 
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[30]); 
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[15]); 
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[23]); 
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[26]); 
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[11]); 
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[3]); 
    for (i = 0; i < 10; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[15]); 
    for (i = 0; i < 4; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[4]); 
    for (i = 0; i < 18; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[23]); 
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[20]); 
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[26]); 
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[24]); 
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[2]); 
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[17]); 
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[17]); 
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[13]); 
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[22]); 
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[28]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[19]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[13]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[26]);
    for (i = 0; i < 2; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[0]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[0]);
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[3]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[7]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[23]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[6]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[21]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[9]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[3]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[2]);
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[16]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[8]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[12]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[14]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[10]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[5]);
    for (i = 0; i < 11; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[25]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[25]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[20]);
    for (i = 0; i < 11; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[18]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[7]);
    for (i = 0; i < 4; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[2]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[6]);
    for (i = 0; i < 8; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[3]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[7]);
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[15]);
    for (i = 0; i < 3; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[1]);
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[28]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[16]);
    for (i = 0; i < 5; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[3]);
    for (i = 0; i < 7; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[14]);
    for (i = 0; i < 9; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[24]);
    for (i = 0; i < 3; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[1]);
    for (i = 0; i < 12; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[22]);
    for (i = 0; i < 6; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[29]);
    for (i = 0; i < 4; i++) fp_sq1(&tt);
    fp_mul2(&tt,&t[2]);
    fp_sq1(&tt);
    fp_sq2(y,&tt);
}

//computing 1/x^2 mod p
void fp_inv_sqare(fp *x)
{
    fp t[31], tt;
    int i;
    // Precomputed table
    fp_sq2(&tt, x);
    fp_mul3(&t[0], x, &tt);
    for (i = 0; i <= 29; i++) fp_mul3(&t[i+1], &t[i], &tt);
    fp_copy(&tt, x);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 27 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 11 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 19 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 5 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 5 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 30 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 8 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 28 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 9 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 16 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 30 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 15 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 26 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 11 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 10 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 15 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 4 ]);
for(i=0; i< 18 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 20 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 26 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 24 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 2 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 13 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 22 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 28 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 19 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 13 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 26 ]);
for(i=0; i< 2 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 0 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 0 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 7 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 6 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 21 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 9 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 2 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 16 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 8 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 12 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 14 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 10 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 5 ]);
for(i=0; i< 11 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 25 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 25 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 20 ]);
for(i=0; i< 11 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 18 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 7 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 2 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 6 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 7 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 15 ]);
for(i=0; i< 3 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 1 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 28 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 16 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 14 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 24 ]);
for(i=0; i< 3 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 1 ]);
for(i=0; i< 12 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 22 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 29 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 12 ]);
fp_sq1(&tt);
fp_sq2(x,&tt);

}

void fp_quartexp(fp *x)
{
    fp t[31], tt;
    int i;
    // Precomputed table
    fp_sq2(&tt, x);
    fp_mul3(&t[0], x, &tt);
    for (i = 0; i <= 29; i++) fp_mul3(&t[i+1], &t[i], &tt);  

fp_copy(&tt, x);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 27 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 11 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 19 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 5 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 5 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 30 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 8 ]);

for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 28 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);

for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 9 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 16 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 30 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 15 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 26 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 11 ]);


for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 10 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 15 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 4 ]);
for(i=0; i< 18 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);


for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 20 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 26 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 24 ]);


for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 2 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 13 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 22 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 28 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 19 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 13 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 26 ]);
for(i=0; i< 2 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 0 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 0 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);


for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 7 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 6 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 21 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 9 ]);

for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 2 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 16 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 8 ]);

for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 12 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 14 ]);


for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 10 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 5 ]);
for(i=0; i< 11 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 25 ]);

for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 25 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 20 ]);

for(i=0; i< 11 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 18 ]);

for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 7 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 2 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 6 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);


for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 7 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 15 ]);
for(i=0; i< 3 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 1 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 28 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 16 ]);

for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);

for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 14 ]);

for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 24 ]);
for(i=0; i< 3 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 1 ]);
for(i=0; i< 12 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 22 ]);


for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 29 ]);

for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 2 ]);

fp_sq2(x,&tt);


}

void fp_inv_test(fp *x)
{
    fp t[31], tt;
    int i;
    // Precomputed table
    fp_sq2(&tt, x);
    fp_mul3(&t[0], x, &tt);
    for (i = 0; i <= 29; i++) fp_mul3(&t[i+1], &t[i], &tt);

    fp_copy(&tt, x);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 27 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 11 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 19 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 5 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 5 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 30 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 8 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 28 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 9 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 16 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 30 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 15 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 26 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 11 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 10 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 15 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 4 ]);
for(i=0; i< 18 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 20 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 26 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 24 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 2 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 17 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 13 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 22 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 28 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 19 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 13 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 26 ]);
for(i=0; i< 2 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 0 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 0 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 7 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 23 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 6 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 21 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 9 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 2 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 16 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 8 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 12 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 14 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 10 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 5 ]);
for(i=0; i< 11 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 25 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 25 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 20 ]);
for(i=0; i< 11 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 18 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 7 ]);
for(i=0; i< 4 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 2 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 6 ]);
for(i=0; i< 8 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 7 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 15 ]);
for(i=0; i< 3 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 1 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 28 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 16 ]);
for(i=0; i< 5 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 3 ]);
for(i=0; i< 7 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 14 ]);
for(i=0; i< 9 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 24 ]);
for(i=0; i< 3 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 1 ]);
for(i=0; i< 12 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 22 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 29 ]);
for(i=0; i< 6 ; i++) fp_sq1(&tt);
fp_mul2(&tt,&t[ 12 ]);
for(i=0; i< 2 ; i++) fp_sq1(&tt);
fp_mul3(x, &tt,x);
 





}